{% set version = "2.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tfdatasets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tfdatasets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tfdatasets/tfdatasets_{{ version }}.tar.gz
  sha256: d40adc21f3d7137fce90bac484f95f51339c2f6c073ce9364e007529b9fd1fe1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-generics
    - r-magrittr
    - r-reticulate >=1.10
    - r-rlang
    - r-tensorflow >=1.13.1
    - r-tfestimators
    - r-tidyselect
  run:
    - r-base
    - r-generics
    - r-magrittr
    - r-reticulate >=1.10
    - r-rlang
    - r-tensorflow >=1.13.1
    - r-tfestimators
    - r-tidyselect

test:
  commands:
    - $R -e "library('tfdatasets')"           # [not win]
    - "\"%R%\" -e \"library('tfdatasets')\""  # [win]

about:
  home: https://github.com/rstudio/tfdatasets
  license: Apache-2.0
  summary: Interface to 'TensorFlow' Datasets, a high-level library for building complex input pipelines from simple, re-usable pieces. See <https://www.tensorflow.org/programmers_guide/datasets> for additional details.
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: tfdatasets
# Type: Package
# Title: Interface to 'TensorFlow' Datasets
# Version: 2.0.0
# Authors@R: c( person("Daniel", "Falbel", role = c("ctb", "cph", "cre"), email = "daniel@rstudio.com"), person("JJ", "Allaire", role = c("aut", "cph"), email = "jj@rstudio.com"), person("Yuan", "Tang", role = c("aut"), email = "terrytangyuan@gmail.com", comment = c(ORCID = "0000-0001-5243-233X")), person("Kevin", "Ushey", role = c("aut"), email = "kevin@rstudio.com"), person("RStudio", role = c("cph", "fnd")), person(family = "Google Inc.", role = c("cph")) )
# Description: Interface to 'TensorFlow' Datasets, a high-level library for building complex input pipelines from simple, re-usable pieces. See <https://www.tensorflow.org/programmers_guide/datasets> for additional details.
# License: Apache License 2.0
# URL: https://github.com/rstudio/tfdatasets
# BugReports: https://github.com/rstudio/tfdatasets/issues
# SystemRequirements: TensorFlow >= 1.4 (https://www.tensorflow.org/)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.1)
# Imports: reticulate (>= 1.10), tensorflow (>= 1.13.1), magrittr, rlang, tidyselect, stats, generics, tfestimators
# RoxygenNote: 7.0.1
# Suggests: testthat, knitr, keras, rsample, rmarkdown, Metrics, dplyr
# VignetteBuilder: knitr
# Config/reticulate: list( packages = list( list(package = "tensorflow", pip = TRUE) ) )
# NeedsCompilation: no
# Packaged: 2019-12-13 14:00:23 UTC; dfalbel
# Author: Daniel Falbel [ctb, cph, cre], JJ Allaire [aut, cph], Yuan Tang [aut] (<https://orcid.org/0000-0001-5243-233X>), Kevin Ushey [aut], RStudio [cph, fnd], Google Inc. [cph]
# Maintainer: Daniel Falbel <daniel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-12-13 14:40:02 UTC
