{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tfdatasets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tfdatasets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tfdatasets/tfdatasets_{{ version }}.tar.gz
  sha256: 59cfbd1a885734f936597ec45751481edd493666a47ab1627fe21b088fc282bb

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-magrittr
    - r-reticulate >=1.10
    - r-rlang
    - r-tensorflow >=1.9
    - r-tidyselect
  run:
    - r-base
    - r-magrittr
    - r-reticulate >=1.10
    - r-rlang
    - r-tensorflow >=1.9
    - r-tidyselect

test:
  commands:
    - $R -e "library('tfdatasets')"           # [not win]
    - "\"%R%\" -e \"library('tfdatasets')\""  # [win]

about:
  home: https://github.com/rstudio/tfdatasets
  license: Apache-2.0
  summary: Interface to 'TensorFlow' Datasets, a high-level library for  building complex input
    pipelines from simple, re-usable pieces.  See <https://www.tensorflow.org/programmers_guide/datasets>
    for additional details.
  license_family: APACHE

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: tfdatasets
# Type: Package
# Title: Interface to 'TensorFlow' Datasets
# Version: 1.9
# Authors@R: c( person("JJ", "Allaire", role = c("aut", "cre"), email = "jj@rstudio.com"), person("Yuan", "Tang", role = c("aut"), email = "terrytangyuan@gmail.com", comment = c(ORCID = "0000-0001-5243-233X")), person("Kevin", "Ushey", role = c("aut"), email = "kevin@rstudio.com"), person("RStudio", role = c("cph", "fnd")),   person(family = "Google Inc.", role = c("cph")) )
# Description: Interface to 'TensorFlow' Datasets, a high-level library for  building complex input pipelines from simple, re-usable pieces.  See <https://www.tensorflow.org/programmers_guide/datasets> for additional details.
# License: Apache License 2.0
# URL: https://github.com/rstudio/tfdatasets
# BugReports: https://github.com/rstudio/tfdatasets/issues
# SystemRequirements: TensorFlow >= 1.4 (https://www.tensorflow.org/)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.1)
# Imports: reticulate (>= 1.10), tensorflow (>= 1.9), magrittr, rlang, tidyselect, stats
# RoxygenNote: 6.0.1
# Suggests: testthat, knitr, tfestimators, keras
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-08-25 12:24:04 UTC; jjallaire
# Author: JJ Allaire [aut, cre], Yuan Tang [aut] (<https://orcid.org/0000-0001-5243-233X>), Kevin Ushey [aut], RStudio [cph, fnd], Google Inc. [cph]
# Maintainer: JJ Allaire <jj@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-08-25 13:20:03 UTC
