{% set version = "1.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tfdatasets
  version: {{ version|replace("-", "_") }}

source:
  fn: tfdatasets_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tfdatasets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tfdatasets/tfdatasets_{{ version }}.tar.gz
  sha256: 67893095aa813844e32a57d4360a94f82a4dde35b12d37b2abd5ae3fb91f58b6

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-magrittr
    - r-reticulate >=1.3
    - r-rlang
    - r-tensorflow >=1.4.1
    - r-tidyselect

  run:
    - r-base
    - r-magrittr
    - r-reticulate >=1.3
    - r-rlang
    - r-tensorflow >=1.4.1
    - r-tidyselect

test:
  commands:
    - $R -e "library('tfdatasets')"           # [not win]
    - "\"%R%\" -e \"library('tfdatasets')\""  # [win]

about:
  home: https://github.com/rstudio/tfdatasets
  license: Apache-2.0
  summary: Interface to 'TensorFlow' Datasets, a high-level library for  building complex input
    pipelines from simple, re-usable pieces.  See <https://www.tensorflow.org/programmers_guide/datasets>
    for additional details.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
