appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: sgtrGeMyRvT8RxPx2fyOcZz58PqpvQHiUv+rEgjrTM/X0nX60brHs/8jpFmVJoUQ0l0qVlGtzezYCjKAlhTr/CmZOODHazNgaGpYtgOZNKggrQXrd6j+zRVI7yzlxOgmROMYoGZ0E0qJn7KNyv9B0PvsRFnMRUNzDu6aL6cgwwbUkhiEbD8UligYORt0wqijnqS4nUZXwZWmRlGFVhvqLDgu406LYFaCYSGZYqm9yZx71Ixmp/XSlZ7CzX4CMN1y0nzWDncliV3AFi/UjN9FaCogJ1MLlyFawqlCggPICkyEjAG9SxR1XafBLv3emEATxCfqXR/8yCJZXkAcVnumSoXjdy3N/wrY4mMn4aP2L2+ItOXhg0KT5OLEs00+XzPZJTZykvrRbcRLlJP9YAZg4Ld/QCe6T92Q6KyN0LlvRi4qq4I2dGVN1n5zNUJSrqjD/UMSZqLLHo/58Wd6TsOYgjbntwVjFu4j4OiawoiBCo/ShVLa1zCG4OgLtcWerKhSsLe1j77Csy8bnn4xaSffKQFGnc/xVq58pIPyHu5lTGKUDk7HLfiG9Xxb6cL9fbNj0vkk1jwXTNOTRX8b+78WiNunKveVF2ymkgPhWxws4Hu8x7CinmT1+SjImaiOXIvlQfJzJSywjOU/IFbyj1yBa7CG17COsjMWfWrG0HhU+jk=}
